### ISSUE TITLE
LWSC1 - Caroll's Puzzles

### ISSUE THREAD

**Issue by vineetarath** [decodevector/pset#13]
(a) My saucepans are useless.

(b) One who is not a writer could not have written Hamlet.

(c) A rainbow is not worth writing an ode to.

**Comment by remus-lupin** [comment]
Do not leave the solutions in the issues. This space is meant for problems/issues.
Submit your solutions as per the instructions given here: https://github.com/decodevector/pset

**Comment by vineetarath** [comment]
hey, i'm trying to create a folder inside my 'VineetaRath' folder, this was by error - still trying to figure it out.

**Comment by vineetarath** [comment]
there is a find file option, not a create file one...
![screen shot 2018-02-18 at 4 19 33 pm](https://user-images.githubusercontent.com/36075796/36350957-96748b62-14c7-11e8-9f64-23f48e54fb81.png)

so trying to find it in some place i've missed - do delete the 13th issue - i've closed it, will see if i can delete it too

**Comment by remus-lupin** [comment]
Check https://guides.github.com/activities/hello-world/.
You were expected to create branch, folder, and files via desktop GitHub as told earlier.

See https://www.youtube.com/user/GitHubGuides if needed.
