### ISSUE TITLE
DO NOT ATTEMPT to commit on master branch.

### ISSUE THREAD

**Issue by remus-lupin** [decodevector/pset#16]
Commit to your own branches and send me your pull request. I will merge them to master after reviewing solutions. Also, do not merge your pull requests to master.

**Comment by apoorva-a98** [comment]
okay. what do i do now?

**Comment by remus-lupin** [comment]
@apoorva-a98 Send me a pull request like Simran did.

**Comment by apoorva-a98** [comment]
i hope it happened now?

**Comment by apoorva-a98** [comment]
changed branch name too.

**Comment by remus-lupin** [comment]
@apoorva-a98 Checking.
