### ISSUE TITLE
Pull request query

### ISSUE THREAD

**Issue by simraan9** [decodevector/pset#18]
If I'm understanding correctly, aren't we supposed to merge our pull request with your username instead of master? I'm unable to change that. 
![screenshot 79](https://user-images.githubusercontent.com/22179784/36352481-b6be0afc-14df-11e8-8f98-28c511cfe73d.png)

Also, I don't know if what I've been able to do is right or not! Help!

**Comment by remus-lupin** [comment]
@simraan9 You have successfully sent your pull request. I am now responsible to merge after reviewing. However, I have left a comment for you to fix a change. I will review your branch after that.
